#!/bin/sh
#bspc rule -r "*"

if xrandr -q | grep "HDMI-1 connected"; then
  xrandr --output eDP-1 --right-of HDMI-1
  bspc monitor HDMI-1 -d I II III IV V VI VII
  bspc monitor eDP-1 -d I II III


else
  bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi

~/.config/polybar/shapes/./launch.sh
sxhkd &
#deadd-notification-center &
#compton --experimental-backends &
picom --experimental-backends &
#polybar example &


bspc config border_width         1
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
#bspc config border_radius 10


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#CUSTOM

. "${HOME}/.cache/wal/colors.sh"
bspc config bottom_padding 1
bspc config top_padding 3
bspc config left_padding 2
bspc config right_padding 2

bspc config focus_follows_pointer true
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

# Window Rules
#sleep 1
#wmctrl -r Spotify -t 9 
#exit
#bspc rule -a Spotify state=floating rectangle=500x500+500+500 sticky=off
#bspc rule -a Alacritty state=floating rectangle 600x900+200+50 sticky=off
bspc rule -a Pavucontrol state=floating rectangle 200x200+50+50 sticky=off 


#enable touchpad tapping and natural scrolling
xinput set-prop "CUST0001:00 04F3:30AA Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "CUST0001:00 04F3:30AA Touchpad" "libinput Natural Scrolling Enabled" 1

~/.config/polybar/shapes/scripts/./pywal.sh ~/Pictures/AT

conky
dunst
